export const users = [
  {
    name: "John",
    image: "/placeholder.svg?height=32&width=32",
  },
  {
    name: "Sarah",
    image: "/placeholder.svg?height=32&width=32",
  },
  {
    name: "Mike",
    image: "/placeholder.svg?height=32&width=32",
  },
  {
    name: "Emma",
    image: "/placeholder.svg?height=32&width=32",
  },
]

export const initialEvents = [
  {
    id: 1,
    title: "Email design",
    start: "9:00",
    end: "11:20",
    day: 18,
    participants: users.slice(0, 3),
    color: "bg-blue-100",
    description: "Design email templates for the new campaign",
  },
  {
    id: 2,
    title: "Youtube video",
    start: "8:30",
    end: "9:30",
    day: 19,
    participants: [],
    color: "bg-purple-100",
    description: "Record tutorial video for the new feature",
  },
  {
    id: 3,
    title: "Designers meeting",
    start: "9:30",
    end: "10:30",
    day: 19,
    participants: users.slice(1, 3),
    color: "bg-blue-100",
    description: "Weekly design team sync",
  },
  {
    id: 4,
    title: "Breakfast",
    start: "9:30",
    end: "10:30",
    day: 20,
    participants: [],
    color: "bg-blue-100",
    description: "Team breakfast",
  },
  {
    id: 5,
    title: "UX meeting",
    start: "11:30",
    end: "13:00",
    day: 19,
    participants: [],
    color: "bg-blue-100",
    description: "Discuss user experience improvements",
  },
  {
    id: 6,
    title: "Brain storm",
    start: "11:10",
    end: "13:30",
    day: 20,
    participants: users.slice(0, 2),
    color: "bg-blue-100",
    description: "Brainstorming session for new product ideas",
  },
  {
    id: 7,
    title: "Team meeting",
    start: "10:30",
    end: "12:00",
    day: 21,
    participants: users.slice(0, 2),
    color: "bg-purple-100",
    description: "Weekly team sync",
  },
  {
    id: 8,
    title: "Launch Time",
    start: "11:30",
    end: "12:30",
    day: 21,
    participants: [],
    color: "bg-purple-100",
    description: "Product launch preparation",
  },
  {
    id: 9,
    title: "Landing Page",
    start: "9:00",
    end: "10:30",
    day: 22,
    participants: [],
    color: "bg-blue-100",
    description: "Design landing page for new product",
  },
  {
    id: 10,
    title: "Designers meet",
    start: "12:30",
    end: "2:30",
    day: 22,
    participants: [],
    color: "bg-blue-100",
    description: "Design team collaboration session",
  },
  {
    id: 11,
    title: "UX meeting",
    start: "12:00",
    end: "1:30",
    day: 23,
    participants: [],
    color: "bg-purple-100",
    description: "User experience review meeting",
  },
  {
    id: 12,
    title: "Study time",
    start: "9:30",
    end: "11:30",
    day: 23,
    participants: [],
    color: "bg-purple-100",
    description: "Personal study session",
  },
  {
    id: 13,
    title: "Motion design",
    start: "7:30",
    end: "10:30",
    day: 23,
    participants: users.slice(1, 3),
    color: "bg-blue-100",
    description: "Create motion graphics for the new app",
  },
  {
    id: 14,
    title: "New Project",
    start: "10:30",
    end: "12:10",
    day: 23,
    participants: [],
    color: "bg-blue-100",
    description: "Kickoff meeting for the new project",
  },
  {
    id: 15,
    title: "Develop meeting",
    start: "12:30",
    end: "1:30",
    day: 19,
    participants: [],
    color: "bg-purple-100",
    description: "Development team sync",
  },
]

export const days = [
  { name: "TUE", number: "18", date: new Date(2023, 9, 18) },
  { name: "WED", number: "19", date: new Date(2023, 9, 19) },
  { name: "THU", number: "20", date: new Date(2023, 9, 20) },
  { name: "FRI", number: "21", date: new Date(2023, 9, 21) },
  { name: "SAT", number: "22", date: new Date(2023, 9, 22) },
  { name: "SUN", number: "23", date: new Date(2023, 9, 23) },
]

export const categories = [
  { name: "Work", color: "bg-blue-400" },
  { name: "Personal", color: "bg-green-400" },
  { name: "Education", color: "bg-purple-400" },
]

export const calendars = [
  { name: "Daily Tasks", checked: true },
  { name: "Birthdays", checked: true },
  { name: "Tasks", checked: true },
]

